---
    name: build
    on:
      pull_request:
        branches:
          - main
          - release/**
      push:
        branches:
        - main
        - release/**
    jobs:
      build:
        runs-on: ubuntu-22.04
        permissions:
          contents: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 10
              fetch-tags: true
          - name: Tag repository
            shell: bash
            run: |
              OUTPUT=$(docker run -v $PWD:/workdir martoc/semver:1.2.0 calculate --path /workdir)
              TAG_VERSION=$(echo $OUTPUT | jq -r '.next_version')
              TAG_NAME="v$TAG_VERSION"
              TAG_SHA=$(git rev-parse HEAD)

              echo "TAG_VERSION=$TAG_VERSION"
              echo "TAG_NAME=$TAG_NAME"
              echo "TAG_SHA=$TAG_SHA"
              echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_ENV"
              echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
              echo "TAG_SHA=$TAG_SHA" >> "$GITHUB_ENV"

              echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_OUTPUT"
              echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"
              echo "TAG_SHA=$TAG_SHA" >> "$GITHUB_OUTPUT"

              git config user.name github-actions
              git config user.email github-actions@github.com
              git tag $TAG_NAME
              git push --tags --force
