name: build
on:
  pull_request:
    branches:
      - main
      - release/**
  push:
    branches:
    - main
    - release/**

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      TAG_VERSION: ${{ steps.set-version.outputs.TAG_VERSION }}
    steps:
      - name: Set Variable
        id: set-version
        run: |
          export MY_VAR=123
          echo "TAG_VERSION=1.0.0" >> $GITHUB_ENV
          echo "TAG_VERSION=1.0.0" >> $GITHUB_OUTPUT
      - name: Use Variable TAG_VERSION
        run: echo "TAG_VERSION=$TAG_VERSION"
      - name: Use Variable MY_VAR
        run: echo "MY_VAR=$MY_VAR"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use Variable
        run: echo "$TAG_VERSION"
      - name: Use Variable
        run: echo "${{ needs.job1.outputs.TAG_VERSION }}"
