name: build
on:
  pull_request:
    branches:
      - main
      - release/**
  push:
    branches:
    - main
    - release/**

jobs:
  job1:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      TAG_VERSION: ${{ steps.set-version.outputs.TAG_VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 40
          fetch-tags: true
      - uses: martoc/action-tag@v0
        id: set-version

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Show Tag Version
        run: echo "TAG_VERSION=${{ needs.job1.outputs.TAG_VERSION }}"
