name: build
on:
  pull_request:
    branches:
      - main
      - release/**
  push:
    branches:
    - main
    - release/**

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: |
          export MY_VAR=123
          echo "MY_VARIABLE=my_value" >> $GITHUB_ENV #this is workflow scoped
      - name: Use Variable MY_VARIABLE
        run: echo "$MY_VARIABLE"
      - name: Use Variable MY_VAR
        run: echo "$MY_VAR"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use Variable
        run: echo "$MY_VARIABLE"
